routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/manage','HomeController@index')->name('manage');

Route::get('/backup','BackupController@create')->name('backup');

Route::get('/logout', 'Auth\LoginController@logout');

Route::post('/report',[
    'uses'=>'HomeController@report',
    'as'=>'report'
    ]);
Route::post('/insurancereport',[
    'uses'=>'HomeController@insurancereport',
    'as'=>'reports'
]);

Route::post('/ticketReport',[
    'uses'=>'HomeController@ticketReport',
    'as'=>'reportss'
]);
Route::get('/export',[
    'uses'=>'HomeController@export',
    'as'=>'export'
]);
Route::get('/exportInsurance',[
    'uses'=>'HomeController@exportInsurance',
    'as'=>'exportInsurance'
]);
Route::get('/ticketReportPrint',[
    'uses'=>'HomeController@ticketReportPrint',
    'as'=>'ticketReportPrint'
]);
Route::resource('vehicle','VehicleController');
Route::resource('owner','OwnerController');
Route::resource('driver','DriverController');
Route::resource('accident','AccidentController');
Route::resource('tripfee','Tripfeecontroller');
Route::resource('ticket','TicketController');

Auth::routes();

app/vehicles.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class vehicles extends Model
{
    //
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\vehicles;
use App\owner;
use App\drivers;
use App\Tripfee;
use App\Tickets;
use App\Accident;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Session;
class VehicleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response



     */

     public function __construct()
     {
         $this->middleware('auth');
     }
    public function index()
    {
      $vehicles=vehicles::all();
        $expired = HomeController::extract_expired_vehicles();
        return view('vehicle/show',compact('vehicles','expired'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $expired = HomeController::extract_expired_vehicles();
      return view('vehicle/add',compact('expired'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $message= ['v_no.required'=>'Vehicle Number is Required',
                  'v_no.unique'=>'The vehicle number has already been taken',
                'v_company.required'=>'vehicle company name is Required',
                'v_model.required'=>'vehicle model name is Required',
                'v_type.required'=>'vehicle type  is Required',
                  'from.required'=>'vehicle Route from  is Required',
                      'to.required'=>'vehicle Route to  is Required',
                      'date_from.required'=>'vehicle insurance start date is required',
                      'date_to.required' =>'vehicle insurance end date is required',
                      'chassis_no.required' =>'vehicle chassis number  is required',
              ];
      $this->validate($request,[
       'v_no'=>'required|unique:vehicles|',
         'v_company'=>'required',
         'v_model'=>'required',
         'chassis_no'=>'required',
         'v_type'=>'required',
         'from'=>'required',
         'to'=>'required',
         'date_from'=>'required',
         'date_to'=>'required',
     ],$message);


      $vehicles= new vehicles;
      $vehicles->v_no = $request->v_no;
      $vehicles->company_name = $request->v_company;
      $vehicles->model =$request->v_model;
      $vehicles->chassis_no =$request->chassis_no;
      $vehicles->v_type=$request->v_type;
      $vehicles->route_from=$request->from;
      $vehicles->route_to=$request->to;
      $vehicles->date_from= date('Y-m-d',strtotime($request->date_from));
      $vehicles->date_to=date('Y-m-d',strtotime($request->date_to));

      $vehicles->save();

      Session::flash('message', 'New vehicle has been successfully created.');
      return redirect(route('owner.create'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $expired = HomeController::extract_expired_vehicles();
        $vehicle = vehicles::where('v_no', $id)->first();
        $owners = owner::all();
        foreach($owners as $owner){
            $v_no_array = unserialize($owner->v_no);
            foreach($v_no_array as $v_no){
                if($v_no == $id){
                    $owner_detail = [
                        'name' => $owner->name,
                        'address' => $owner->address,
                        'contact' => $owner->contact_no,
                    ];
                    break;
                }
            }
        }
        $drivers = drivers::all();
        foreach($drivers as $driver){
            $v_no_array = unserialize($driver->v_no);
            foreach($v_no_array as $v_no){
                if($v_no == $id){
                    $driver_detail[] = [
                        'card_no' => $driver->card_no,
                        'name' => $driver->name,
                        'address' => $driver->address,
                        'contact' => $driver->contact_no,
                        'license_no' => $driver->license_no,
                        'age' => $driver->age,
                        'gender' => $driver->gender,
                        'blood_group' => $driver->blood_group,
                        'experience' => $driver->experience,
                        'type' => $driver->type,
                        'card_expiry_date' => $driver->end_date,
                    ];
                    break;
                }
            }
        }
        $tripfees = Tripfee::where('v_no','=',$id)->get();
        $accidents = Accident::where('v_no','=',$id)->get();
        $tickets = Tickets::where('v_no','=',$id)->get();

        return view('vehicle/details',compact('expired','vehicle','owner_detail','driver_detail','tripfees','accidents','tickets'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $vehicles=vehicles::where('id', $id)->first();
        $expired = HomeController::extract_expired_vehicles();
        return view('vehicle.edit',compact('vehicles','expired'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


        $this->validate($request,[
         'v_no'=>'required',
           'v_company'=>'required',
           'v_model'=>'required',
           'chassis_no'=>'required',
           'v_type'=>'required',
           'from'=>'required',
           'to'=>'required',
        ]);


        $vehicles= vehicles::find($id);
        $vehicles->v_no = $request->v_no;
        $vehicles->company_name = $request->v_company;
        $vehicles->model =$request->v_model;
        $vehicles->chassis_no =$request->chassis_no;
        $vehicles->v_type=$request->v_type;
        $vehicles->route_from=$request->from;
        $vehicles->route_to=$request->to;
        $vehicles->date_from= date('Y-m-d',strtotime($request->date_from));
        $vehicles->date_to=date('Y-m-d',strtotime($request->date_to));
        $vehicles->save();

        Session::flash('message', 'Vehicle has been successfully updated.');
        return redirect(route('vehicle.index'));


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $v = vehicles::select('v_no')->where('id',$id)->get();
        $owners = owner::all();
        foreach($owners as $owner){
            $v_no_array = unserialize($owner->v_no);
            for($i = 0; $i < count($v_no_array); $i++){
                if($v_no_array[$i] == $v[0]->v_no){
                    if(count($v_no_array) == 1){
                        $owner->delete();
                        break;
                    }else{
                        unset($v_no_array[$i]); // remove item at index 0
                        $v_no_array = array_values($v_no_array);
                        $owner->v_no = serialize($v_no_array);
                        $owner->save();
                        break;
                    }
                }
            }
        }

        vehicles::where('id', $id)->delete();
        drivers::where('v_no', $v[0]->v_no)->delete();
        Session::flash('flash_message','Vehicle has been successfully deleted.');
        return redirect()->back();
    }
}

resources/views/vehicle/add.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>Add new vehicle</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Vehicle</li>
                <li class="active">Add</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <form action="{{route('vehicle.store')}}" method="post" name="form">
                        {{ csrf_field()}}

                        <div class="form-group">


                            <label for="vehicle-number">Number<span class="astric">*</span>  </label>@if($errors->has('v_no'))
                                <span class="error">  {{  $errors->first('v_no')}}</span>
                            @endif
                            <input id="vehicle-number" class="form-control" type="text" name="v_no" placeholder="Eg. Lu 2 Pa 2345" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-company">Company<span class="astric">*</span> </label>@if($errors->has('v_company'))
                                <span class="error">  {{  $errors->first('v_company')}}</span>
                            @endif
                            <input id="vehicle-company" class="form-control" type="text" name="v_company" placeholder="Eg. Tata, Ford, Suzuki" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-model">Model<span class="astric">*</span> </label>
                            @if($errors->has('v_company'))
                                <span class="error">  {{  $errors->first('v_model')}}</span>
                            @endif
                            <input id="vehicle-model" class="form-control" type="text" name="v_model" placeholder="Eg. Hyundai Elite i20" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-model">Chassis Number<span class="astric">*</span> </label>
                            @if($errors->has('chassis_no'))
                                <span class="error">  {{  $errors->first('chassis_no')}}</span>
                            @endif
                            <input id="chassis_no" class="form-control" type="text" name="chassis_no" placeholder="Eg. SV30-0169266 " />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-type">Type<span class="astric">*</span> </label>
                            @if($errors->has('v_company'))
                                <span class="error">  {{  $errors->first('v_type')}}</span>
                            @endif
                            <input id="vehicle-type" class="form-control" type="text" name="v_type" placeholder="Eg. Jeep, Mini-Bus, Micro-Bus" />
                        </div>

                        <div class="form-horizontal row">
                            <label class="col-lg-12">Insurance</label>
                            <div class="form-group col-md-6">
                                <label for="vehicle-route-from" class="col-sm-2 control-label">From<span class="astrict">*</span> </label>
                                @if($errors->has('date_from'))
                                    <span class="error">  {{  $errors->first('date_from')}}</span>
                                @endif
                                <div class="input-group date">

                                    <div class="input-group-addon" >
                                        <i class="fa fa-calendar"></i>
                                    </div>

                                    <input type="text" class="form-control pull-right" id="from" name="date_from">

                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-6">
                                <label for="vehicle-route-from" class="col-sm-2 control-label">To<span class="astrict">*</span> </label>
                                @if($errors->has('date_to'))
                                    <span class="error">  {{  $errors->first('date_to')}}</span>
                                @endif
                                <div class="input-group date">

                                    <div class="input-group-addon" >
                                        <i class="fa fa-calendar"></i>
                                    </div>

                                    <input type="text" class="form-control pull-right" id="to" name="date_to">

                                </div>
                                <!-- /.input group -->
                            </div>

                        </div>

                        <div class="form-horizontal">
                            <label>Route</label>
                            <div class="form-group">
                                <label for="vehicle-route-from" class="col-sm-1 control-label">From<span class="astric">*</span> </label>
                                @if($errors->has('v_company'))
                                    <span class="error">  {{  $errors->first('from')}}</span>
                                @endif
                                <div class="col-sm-11">
                                    <input type="text" class="form-control" id="vehicle-route-from" placeholder="Eg. Butwal" name="from">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="vehicle-route-to" class="col-sm-1 control-label">To<span class="astric">*</span> </label>
                                @if($errors->has('v_company'))
                                    <span class="error">  {{  $errors->first('to')}}</span>
                                @endif
                                <div class="col-sm-11">
                                    <input type="text" class="form-control" id="vehicle-route-to" placeholder="Eg. Kathmandu" name="to">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" name="submit-vehicle" value="Submit" />

                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(function () {




            $("#from").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",
                endDate:'today',
                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var startDate = new Date(selected.date.valueOf());
                $('#to').datepicker('setStartDate', startDate);
            }).on('clearDate', function (selected) {
                $('#to').datepicker('setStartDate', null);
            });

            $("#to").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",

                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var endDate = new Date(selected.date.valueOf());
                $('#from').datepicker('setEndDate', endDate);
            }).on('clearDate', function (selected) {
                $('#from').datepicker('setEndDate', null);

            });

        });
    </script>

@endsection

resources/views/vehicle/edit.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>Edit vehicle details</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Vehicle</li>
                <li class="active">Edit</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <form action="{{route('vehicle.update',$vehicles->id)}}" method="post" name="form">
                        {{ csrf_field()}}
                        {{ method_field('PATCH')}}
                        <h2>Add new vehicle</h2>
                        <div class="form-group">
                            <label for="vehicle-number">Number</label>
                            <input id="vehicle-number" class="form-control" type="text"  name="v_no" placeholder="Eg. Lu 2 Pa 2345" value="{{$vehicles->v_no}}" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-company">Company</label>
                            <input id="vehicle-company" class="form-control" type="text" name="v_company" value="{{$vehicles->company_name }}" placeholder="Eg. Tata, Ford, Suzuki" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-model">Model</label>
                            <input id="vehicle-model" class="form-control" type="text" value="{{$vehicles->model }}" name="v_model" placeholder="Eg. Hyundai Elite i20" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-model">Chassis Number</label>
                            <input id="chassis_no" class="form-control" type="text" value="{{$vehicles->chassis_no }}" name="chassis_no" placeholder="Eg. ss34-53-42" />
                        </div>
                        <div class="form-group">
                            <label for="vehicle-type">Type</label>
                            <input id="vehicle-type" class="form-control" type="text" name="v_type" value="{{$vehicles->v_type }}" placeholder="Eg. Jeep, Mini-Bus, Micro-Bus" />
                        </div>
                        <div class="form-horizontal row">
                            <label class="col-lg-12">Insurance</label>
                            <div class="form-group col-md-6">
                                <label for="vehicle-route-from" class="col-sm-2 control-label">From<span class="astrict">*</span> </label>
                                @if($errors->has('date_from'))
                                    <span class="error">  {{  $errors->first('date_from')}}</span>
                                @endif
                                <div class="input-group date">

                                    <div class="input-group-addon" >
                                        <i class="fa fa-calendar"></i>
                                    </div>

                                    <input type="text" class="form-control pull-right" id="from" name="date_from" value="{{ $vehicles->date_from }}">

                                </div>
                                <!-- /.input group -->
                            </div>
                            <div class="form-group col-md-6">
                                <label for="vehicle-route-from" class="col-sm-2 control-label">To<span class="astrict">*</span> </label>
                                @if($errors->has('date_to'))
                                    <span class="error">  {{  $errors->first('date_to')}}</span>
                                @endif
                                <div class="input-group date">

                                    <div class="input-group-addon" >
                                        <i class="fa fa-calendar"></i>
                                    </div>

                                    <input type="text" class="form-control pull-right" id="to" name="date_to" value="{{ $vehicles->date_to }}">

                                </div>
                                <!-- /.input group -->
                            </div>

                        </div>
                        <div class="form-horizontal">
                            <label>Route</label>
                            <div class="form-group">
                                <label for="vehicle-route-from" class="col-sm-1 control-label">From</label>
                                <div class="col-sm-11">
                                    <input type="text" class="form-control" id="vehicle-route-from" value="{{$vehicles->route_from }}" placeholder="Eg. Butwal" name="from">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="vehicle-route-to" class="col-sm-1 control-label">To</label>

                                <div class="col-sm-11">
                                    <input type="text" class="form-control" id="vehicle-route-to" value="{{$vehicles->route_to }}" placeholder="Eg. Kathmandu" name="to">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" name="submit-vehicle" value="Submit" />

                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(function () {




            $("#from").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",
                endDate:'today',
                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var startDate = new Date(selected.date.valueOf());
                $('#to').datepicker('setStartDate', startDate);
            }).on('clearDate', function (selected) {
                $('#to').datepicker('setStartDate', null);
            });

            $("#to").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",

                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var endDate = new Date(selected.date.valueOf());
                $('#from').datepicker('setEndDate', endDate);
            }).on('clearDate', function (selected) {
                $('#from').datepicker('setEndDate', null);

            });

        });
    </script>


@endsection

resources/views/vehicle/show.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <section class="content-header">
            <h1>Vehicles</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Vehicle</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-body">
                            @if(Session::has('message'))
                                <p class="message"></p>
                                <div class="alert alert-success alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h4><i class="icon fa fa-check"></i> Success</h4>
                                    {{ Session::get('message') }}
                                </div>
                            @endif
                            <table id="example1" class="table table-bordered table-striped ">
                                <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Vehicle No</th>
                                    <th>Company Name</th>
                                    <th>Vehicle Model</th>
                                    <th>chassis Number</th>
                                    <th>vehicle Type</th>
                                    <th>Route From</th>
                                    <th>Route To</th>
                                    <th>Registered Date</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($vehicles as $vehicle)

                                    <?php
                                    $currnet_data = date('Y-m-d');
                                    $last_date = $vehicle->date_to;

                                    $dateTimestamp1 = strtotime($currnet_data);
                                    $dateTimestamp2 = strtotime($last_date);
                                    $diff= $dateTimestamp2-$dateTimestamp1;
                                    $days = floor($diff / (60 * 60 * 24));

                                    //echo $diff;
                                    if ($days<=0)
                                    {
                                        $expired  = TRUE;

                                    }

                                    else {
                                        $expired  = FALSE;


                                    }


                                    ?>




                                    <tr <?php if($expired){echo 'style="background: #f4ab90;"';} ?> >



                                        <a href="#"><td>{{$loop->index+1}}</td></a>
                                        <td><a href="{{ route('vehicle.show',$vehicle->v_no) }}">{{$vehicle->v_no}}</a></td>
                                        <td>{{$vehicle->company_name }}
                                        </td>
                                        <td>{{$vehicle->model }}</td>
                                          <td>{{$vehicle->chassis_no }}</td>
                                        <td> {{$vehicle->v_type  }}</td>
                                        <td>{{$vehicle->route_from  }}</td>
                                        <td>{{$vehicle->route_to  }}</td>
                                        <td>{{$vehicle->created_at  }}</td>
                                        <td>
                                          @php $type= Auth::user()->user_type; @endphp
                                          @if($type=='admin')
                                            <a href="{{route('vehicle.edit',$vehicle->id)}}">   <i class="fa fa-fw fa-edit"></i></a>||
                                            <form id="delete-item{{$vehicle->id}}"  action="{{route('vehicle.destroy',$vehicle->id)}}" style="Display:none"  method="post">
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}

                                            </form>
                                            <a href="" onclick="
                                                    if (confirm('Are you sure, You want to delete this ?'))
                                                    {
                                                    event.preventDefault();
                                                    document.getElementById('delete-item{{$vehicle->id}}').submit();
                                                    }
                                                    else{
                                                    event.preventDefault();
                                                    }

                                                    ">

                                                <i class="fa fa-fw fa-trash"></i></a>
                                                @endif
                                        </td>
                                    </tr>
                                @endforeach()

                                </tfoot>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>


    <style>
        .expired{
            background: #f4ab90;

        }
    </style>
@endsection