routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/manage','HomeController@index')->name('manage');

Route::get('/backup','BackupController@create')->name('backup');

Route::get('/logout', 'Auth\LoginController@logout');

Route::post('/report',[
    'uses'=>'HomeController@report',
    'as'=>'report'
    ]);
Route::post('/insurancereport',[
    'uses'=>'HomeController@insurancereport',
    'as'=>'reports'
]);

Route::post('/ticketReport',[
    'uses'=>'HomeController@ticketReport',
    'as'=>'reportss'
]);
Route::get('/export',[
    'uses'=>'HomeController@export',
    'as'=>'export'
]);
Route::get('/exportInsurance',[
    'uses'=>'HomeController@exportInsurance',
    'as'=>'exportInsurance'
]);
Route::get('/ticketReportPrint',[
    'uses'=>'HomeController@ticketReportPrint',
    'as'=>'ticketReportPrint'
]);
Route::resource('vehicle','VehicleController');
Route::resource('owner','OwnerController');
Route::resource('driver','DriverController');
Route::resource('accident','AccidentController');
Route::resource('tripfee','Tripfeecontroller');
Route::resource('ticket','TicketController');

Auth::routes();

app/Tickets.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tickets extends Model
{
    //
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\vehicles;
use App\Tickets;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
         $this->middleware('auth');
     }
     
    public function index()
    {
        $tickets = Tickets::all();
        $expired = HomeController::extract_expired_vehicles();
        return view('ticket.show',compact('tickets','expired'));
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vehicles = vehicles::all();
        $tickets = DB::table('tickets')
            ->select('particular')
            ->groupBy('particular')
            ->get();

        $expired = HomeController::extract_expired_vehicles();
        return view('ticket.add',compact('vehicles','expired','tickets'));
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $message= [
           /* 'v_no.required'=>'Vehicle Number is Required.',*/
            'particular.required'=>'Particular is Required.',
            'name.required'=>'Name is required',
            'date.required'=>'Date is Required.',
            'amount.required'=>'Amount is Required.',
        ];

        $this->validate($request,[
          /*  'v_no'=>'required',*/
            'particular'=>'required',
            'name'=>'required',
            'date'=>'required',
            'amount'=>'required',
        ],$message);

        $ticket = new Tickets;
        $ticket->v_no = $request->v_no;
        $ticket->particular = $request->particular;
        $ticket->name = $request->name;
        $ticket->date = $request->date;
        $ticket->amount = $request->amount;



        $ticket->save();

        Session::flash('message', 'New ticket has been successfully created.');
        return redirect(route('ticket.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ticket = Tickets::where('id','=',$id)->first();

        return view('print-ticket-receipt', compact('ticket'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicles = vehicles::all();
        $tickets = Tickets::all();
        $details = Tickets::where('id', $id)->first();
        $expired = HomeController::extract_expired_vehicles();
        return view('ticket.edit',compact('vehicles','details','expired','tickets'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $message= [
          /*  'particular.required'=>'Particular is Required.',*/
            'name.required'=>'Name is required',
            'date.required'=>'Date is Required.',
            'amount.required'=>'Amount is Required.',
        ];

        $this->validate($request,[
            /*'v_no'=>'required',*/
            'particular'=>'required',
            'name'=>'required',
            'date'=>'required',
            'amount'=>'required',
        ],$message);

        $ticket = Tickets::find($id);
        $ticket->v_no = $request->v_no;
        $ticket->particular = $request->particular;
        $ticket->name = $request->name;
        $ticket->date = $request->date;
        $ticket->amount = $request->amount;

        $ticket->save();

        Session::flash('message', 'Ticket details has been successfully updated.');
        return redirect(route('ticket.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tickets::where('id', $id)->delete();
        return redirect()->back();
    }
}

resources/views/ticket/add.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Add new ticket
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Ticket</a></li>
                <li><a href="#">Add</a></li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                    {{--<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>--}}
                    <!-- /.box-header -->
                        <div class="box-body">
            <form action="{{route('ticket.store')}}" method="POST">
                <div class="form-group">
                    <label>Vehicle Number</label>

                    {{--@if($errors->has('v_no'))
                        <span class="error">  *{{  $errors->first('v_no')}}</span>
                    @endif--}}

                    <select class="form-control select2 select2-hidden-accessible" name="v_no" id="v_number" style="width: 100%;">
                        
                        <option value="" >Select Vehicle No</option>
                        @forelse($vehicles as $vehicle)
                            <option value="{{$vehicle->v_no}}">{{$vehicle->v_no}}</option>
                        @empty
                            <option>Not Found</option>
                        @endforelse
                    </select>
                </div>
                <div class="form-group">
                    <label for="particular">Particular</label>
                    @if($errors->has('particular'))
                        <span class="error">  *{{  $errors->first('particular')}}</span>
                    @endif

                    <select class="form-control particular-select" name="particular" id="particular" >
                        style="width: 100%;">
                        <option value="">Select your subject.</option>
                        @forelse($tickets as $ticket)
                            <option value="{{$ticket->particular}}">{{$ticket->particular}}</option>
                        @empty
                            <option disabled>Not Found</option>
                        @endforelse
                    </select>
                    <input id="particular" class="form-control particular-text" type="text" name="particular" placeholder="Eg. Application" disabled />

                    <button style="margin:10px 0;" type="button" class="btn btn-default" id="add-new-btn">Add New</button>
                    <button style="margin:10px 0;" type="button" class="btn btn-default" id="choose-existing-btn">Choose Existing</button>
                </div>
                <div class="form-group">
                    <label for="name">Name</label>

                    @if($errors->has('name'))
                        <span class="error">  *{{  $errors->first('name')}}</span>
                    @endif

                    <input id="name" class="form-control" type="text" name="name" placeholder="Eg.Mohan Rana Chhetri" />

                </div>
                <div class="form-group">
                    <label for="amount">Amount</label>
                    @if($errors->has('amount'))
                        <span class="error">  *{{  $errors->first('amount')}}</span>
                    @endif
                    <input id="amount" class="form-control" type="text" name="amount" placeholder="Eg. 10" />
                </div>
                <div class="form-group">
                    <label for="date">Date</label>
                    @if($errors->has('date'))
                        <span class="error">  {{  $errors->first('date')}}</span>
                    @endif
                    <div class="input-group date">

                        <div class="input-group-addon" >
                            <i class="fa fa-calendar"></i>
                        </div>

                        <input type="text" class="form-control pull-right" id="from" name="date">

                    </div>
                    <!-- /.input group -->
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="submit-owner" value="Submit" />
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </div>
            </form>
                        </div></div></div></div>
        </section>
    </div>
    <script>
        $(function () {


            $('.select2').select2();

            $("#from").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",
                endDate:'today',
                startDate:'today',
                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var startDate = new Date(selected.date.valueOf());
                $('#to').datepicker('setStartDate', startDate);
            }).on('clearDate', function (selected) {
                $('#to').datepicker('setStartDate', null);
            });



        });
    </script>
    <style>
        .particular-text,#choose-existing-btn{display:none;}
    </style>
    <script>
        $("#add-new-btn").click(function(){
            $('.particular-select').hide();
            $('.particular-select').prop('disabled','true');
            $('.particular-text').show();
            $('.particular-text').removeAttr('disabled');
            $('#choose-existing-btn').show();
            $('#add-new-btn').hide();
        });
        $("#choose-existing-btn").click(function(){
            $('.particular-select').show();
            $('.particular-select').removeAttr('disabled');
            $('.particular-text').hide();
            $('.particular-text').prop('disabled','true');
            $('#choose-existing-btn').hide();
            $('#add-new-btn').show();
        });
    </script>

@endsection

resources/views/ticket/edit.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Edit ticket details</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Ticket</li>
                <li class="active">Edit</li>
            </ol>
        </section>
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                    {{--<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>--}}
                    <!-- /.box-header -->
                        <div class="box-body">
                            <form action="{{route('ticket.update',$details["id"])}}" method="POST">
                                {{ csrf_field()}}
                                {{ method_field('PATCH')}}
                                <div class="form-group">
                                    <label>Vehicle Number</label>

                                    <select class="form-control" name="v_no" id="v_number" >
                                        style="width: 100%;">
                                        @foreach($vehicles as $vehicle)
                                            @if($details->v_no === $vehicle->v_no)
                                                <option selected>{{ $vehicle->v_no }}</option>
                                            @else
                                                <option>{{ $vehicle->v_no }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="particular">Particular</label>
                                    @if($errors->has('particular'))
                                        <span class="error">  *{{  $errors->first('particular')}}</span>
                                    @endif

                                    <select class="form-control particular-select" name="particular" id="particular" >
                                        style="width: 100%;">
                                        <option>Select your subject.</option>
                                        @foreach($tickets as $ticket)
                                            @if($ticket->particular === $details->particular)
                                                <option selected value="{{ $ticket->particular }}">{{ $ticket->particular }}</option>
                                            @else
                                                <option value="{{ $ticket->particular }}">{{ $ticket->particular }}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                    <input id="particular" class="form-control particular-text" type="text" name="particular" placeholder="Eg. Application" value="{{ $details["particular"] }}" disabled />

                                    <button style="margin:10px 0;" type="button" class="btn btn-default" id="add-new-btn">Add New</button>
                                    <button style="margin:10px 0;" type="button" class="btn btn-default" id="choose-existing-btn">Choose Existing</button>
                                </div>

                                <div class="form-group">
                                    <label for="name">Name</label>

                                    @if($errors->has('name'))
                                        <span class="error">  *{{  $errors->first('name')}}</span>
                                    @endif

                                    <input id="name" class="form-control" type="text" name="name" placeholder="Eg.Mohan Rana Chhetri" value="{{ $details["name"] }}" />

                                </div>
                                <div class="form-group">
                                    <label for="amount">Amount</label>
                                    @if($errors->has('amount'))
                                        <span class="error">  *{{  $errors->first('amount')}}</span>
                                    @endif
                                    <input id="amount" class="form-control" type="text" name="amount" placeholder="Eg. 10" value="{{ $details["amount"] }}" />
                                </div>
                                <div class="form-group">
                                    <label for="date">From</label>
                                    @if($errors->has('date'))
                                        <span class="error">  {{  $errors->first('date')}}</span>
                                    @endif
                                    <div class="input-group date">

                                        <div class="input-group-addon" >
                                            <i class="fa fa-calendar"></i>
                                        </div>

                                        <input type="text" class="form-control pull-right" id="from" name="date" value="{{ $details["date"] }}" />

                                    </div>
                                    <!-- /.input group -->
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-primary" name="submit-owner" value="Submit" />
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(function () {




            $("#from").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",
                endDate:'today',
                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var startDate = new Date(selected.date.valueOf());
                $('#to').datepicker('setStartDate', startDate);
            }).on('clearDate', function (selected) {
                $('#to').datepicker('setStartDate', null);
            });

            $("#to").datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayBtn: "linked",

                todayHighlight: true,
            }).on('changeDate', function (selected) {
                var endDate = new Date(selected.date.valueOf());
                $('#from').datepicker('setEndDate', endDate);
            }).on('clearDate', function (selected) {
                $('#from').datepicker('setEndDate', null);

            });

        });
    </script>
    <style>
        .particular-text,#choose-existing-btn{display:none;}
    </style>
    <script>
        $("#add-new-btn").click(function(){
            $('.particular-select').hide();
            $('.particular-select').prop('disabled','true');
            $('.particular-text').show();
            $('.particular-text').removeAttr('disabled');
            $('#choose-existing-btn').show();
            $('#add-new-btn').hide();
        });
        $("#choose-existing-btn").click(function(){
            $('.particular-select').show();
            $('.particular-select').removeAttr('disabled');
            $('.particular-text').hide();
            $('.particular-text').prop('disabled','true');
            $('#choose-existing-btn').hide();
            $('#add-new-btn').show();
        });
    </script>


@endsection

resources/views/ticket/show.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Tickets
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Ticket</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                    {{--<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>--}}
                    <!-- /.box-header -->
                        <div class="box-body">
                            @if(Session::has('message'))
                                <p class="message"></p>
                                <div class="alert alert-success alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h4><i class="icon fa fa-check"></i> Success</h4>
                                    {{ Session::get('message') }}
                                </div>
                            @endif
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.N</th>
                                    <th>Particular</th>
                                    <th>Name</th>
                                    <th>Amount</th>
                                     <th>Date</th>
                                    <th>Vehicle No.</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($tickets as $ticket)
                                    <tr>
                                        <td>{{$loop->index+1 }}</td>
                                        <td>{{ $ticket->particular }}</td>
                                        <td>{{$ticket->name}}</td>
                                        <td>{{$ticket->amount}}</td>
                                        <td>{{$ticket->date}}</td>
                                        <td>{{$ticket->v_no}}</td>
                                        <td>
                                          @php $type= Auth::user()->user_type; @endphp
                                          @if($type=='admin')

                                            <form id="delete-item{{$ticket->id}}"  action="{{route('ticket.destroy',$ticket->id)}}" style="Display:none"  method="post">
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}

                                            </form>
                                            <a href="" onclick="
                                                    if (confirm('Are you sure, You want to delete this ?'))
                                                    {
                                                    event.preventDefault();
                                                    document.getElementById('delete-item{{$ticket->id}}').submit();
                                                    }
                                                    else{
                                                    event.preventDefault();
                                                    }

                                                    ">

                                                <i class="fa fa-fw fa-trash"></i>||
                                                     @endif
                                                <a href="{{ route('ticket.show',$ticket->id) }}" target="_blank"><i class="fa fa-print" aria-hidden="true"></i></a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        No data Are Found
                                    </tr>
                                @endforelse
                                </tbody>
                                {{--<tfoot>
                                <tr>
                                    <th>Rendering engine</th>
                                    <th>Browser</th>
                                    <th>Platform(s)</th>
                                    <th>Engine version</th>
                                    <th>CSS grade</th>
                                </tr>
                                </tfoot>--}}
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>
    <script>
        $(function () {
            $('#example1').DataTable();
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            });
        })
    </script>
@endsection