routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/manage','HomeController@index')->name('manage');

Route::get('/backup','BackupController@create')->name('backup');

Route::get('/logout', 'Auth\LoginController@logout');

Route::post('/report',[
    'uses'=>'HomeController@report',
    'as'=>'report'
    ]);
Route::post('/insurancereport',[
    'uses'=>'HomeController@insurancereport',
    'as'=>'reports'
]);

Route::post('/ticketReport',[
    'uses'=>'HomeController@ticketReport',
    'as'=>'reportss'
]);
Route::get('/export',[
    'uses'=>'HomeController@export',
    'as'=>'export'
]);
Route::get('/exportInsurance',[
    'uses'=>'HomeController@exportInsurance',
    'as'=>'exportInsurance'
]);
Route::get('/ticketReportPrint',[
    'uses'=>'HomeController@ticketReportPrint',
    'as'=>'ticketReportPrint'
]);
Route::resource('vehicle','VehicleController');
Route::resource('owner','OwnerController');
Route::resource('driver','DriverController');
Route::resource('accident','AccidentController');
Route::resource('tripfee','Tripfeecontroller');
Route::resource('ticket','TicketController');

Auth::routes();

app/owner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class owner extends Model
{

}

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\owner;
use App\vehicles;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Session;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class OwnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


     public function __construct()
     {
         $this->middleware('auth');
     }

    public function index()
    {
        $owners=owner::all();
        $expired = HomeController::extract_expired_vehicles();
        return view('owner.show',compact('owners','expired'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vehicles = vehicles::all();
        $owners = owner::all();
        foreach($vehicles as $vehicle){
            $owned = FALSE;
            foreach($owners as $owner){
                $v_no_array = unserialize($owner->v_no);
                foreach($v_no_array as $v_no){
                    if($v_no == $vehicle->v_no){
                        $owned = TRUE;
                    }
                }
            }
            if(!$owned){
                $unowned_vehicles[] = $vehicle->v_no;
            }
        }
        $expired = HomeController::extract_expired_vehicles();
        return view('owner.add',compact('unowned_vehicles','expired'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $message= [
            'v_no.required'=>'Vehicle Number is Required.',
            'o_name.required'=>'Owner\'s name is Required.',
            'o_address.required'=>'Owner\'s address is Required.',
            'o_contact.required'=>'Owner\'s contact is Required.',
            'insurance.required'=>'Owner\'s insurance field is Required.',
        ];

        $this->validate($request,[
            'v_no'=>'required',
            'o_name'=>'required',
            'o_address'=>'required',
            'o_contact'=>'required',
            'insurance'=>'required',
        ],$message);

        $request->v_no = serialize($request->v_no);

        $owner= new owner;
        $owner->v_no = $request->v_no;
        $owner->name = $request->o_name;
        $owner->address = $request->o_address;
        $owner->contact_no = $request->o_contact;
        $owner->insurance = $request->insurance;

        $owner->save();

        Session::flash('message', 'New owner has been successfully created.');
        return redirect(route('driver.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicles = vehicles::all();
        $owners = owner::all();
        foreach($vehicles as $vehicle){
            $owned = FALSE;
            foreach($owners as $owner){
                $v_no_array = unserialize($owner->v_no);
                foreach($v_no_array as $v_no){
                    if($v_no == $vehicle->v_no){
                        $owned = TRUE;
                    }
                }
            }
            if(!$owned){
                $unowned_vehicles[] = $vehicle->v_no;
            }
        }
        $details = owner::where('id', $id)->first();
        $details->v_no = unserialize($details->v_no);
        $expired = HomeController::extract_expired_vehicles();
        return view('owner.edit',compact('details','unowned_vehicles','expired'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $message= [
            'v_no.required'=>'Vehicle Number is Required.',
            'o_name.required'=>'Owner\'s name is Required.',
            'o_address.required'=>'Owner\'s address is Required.',
            'o_contact.required'=>'Owner\'s contact is Required.',
            'insurance.required'=>'Owner\'s insurance field is Required.',
        ];

        $this->validate($request,[
            'v_no'=>'required',
            'o_name'=>'required',
            'o_address'=>'required',
            'o_contact'=>'required',
            'insurance'=>'required',
        ],$message);

        $request->v_no = serialize($request->v_no);

        $owner = owner::find($id);
        $owner->v_no = $request->v_no;
        $owner->name = $request->o_name;
        $owner->address =$request->o_address;
        $owner->contact_no=$request->o_contact;
        $owner->insurance=$request->insurance;

        $owner->save();

        Session::flash('message', 'Owner details has been successfully updated.');
        return redirect(route('owner.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        owner::where('id', $id)->delete();
        return redirect()->back();
    }
}

resources/views/owner/add.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Add new owner
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Owner</a></li>
                <li><a href="#">Add</a></li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                    {{--<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>--}}
                    <!-- /.box-header -->
                        <div class="box-body">
            <form action="{{route('owner.store')}}" method="POST">
                <div class="form-group">
                    <label>Vehicle Number</label>

                    @if($errors->has('v_no'))
                        <span class="error">  *{{  $errors->first('v_no')}}</span>
                    @endif

                    <select name="v_no[]" class="form-control select2" multiple="multiple"  data-placeholder="Select a Vehicle"
                            style="width: 100%;">
                        <option >Select Vehicle No</option>@if(isset($unowned_vehicles))
                        @forelse($unowned_vehicles as $vehicle)
                            <option >{{$vehicle}}</option>
                        @empty
                            <option>Not Found</option>
                        @endforelse @endif
                    </select>
                </div>
                <div class="form-group">
                    <label for="owner-name">Name</label>
                    @if($errors->has('o_name'))
                        <span class="error">  *{{  $errors->first('o_name')}}</span>
                    @endif
                    <input id="owner-name" class="form-control" type="text" name="o_name" placeholder="Eg. Ram Bahadur" />
                </div>
                <div class="form-group">
                    <label for="owner-address">Address</label>
                    @if($errors->has('o_address'))
                        <span class="error">  *{{  $errors->first('o_address')}}</span>
                    @endif
                    <input id="owner-address" class="form-control" type="text" name="o_address" placeholder="Eg. Butwal-10" />
                </div>
                <div class="form-group">
                    <label for="owner-contact">Contact No.</label>
                    @if($errors->has('o_contact'))
                        <span class="error">  *{{  $errors->first('o_contact')}}</span>
                    @endif
                    <input id="owner-contact" class="form-control" type="text" name="o_contact" placeholder="Eg. 9811111111" />
                </div>
                <div class="form-group">
                    <label for="owner-contact">Insurance</label>
                    <label>
                        <input type="radio" name="insurance" value="1" class="minimal" checked>
                        Yes
                    </label>
                    <label>
                        <input type="radio" name="insurance" value="0" class="minimal">
                        No
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="submit-owner" value="Submit" />
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </div>
            </form>
                        </div></div></div></div>
        </section>
    </div>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' });
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' });
            //Money Euro
            $('[data-mask]').inputmask();

            //Date range picker
            $('#reservation').daterangepicker();
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A' });
            //Date range as a button
            $('#daterange-btn').daterangepicker(
                {
                    ranges   : {
                        'Today'       : [moment(), moment()],
                        'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month'  : [moment().startOf('month'), moment().endOf('month')],
                        'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate  : moment()
                },
                function (start, end) {
                    $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            );

            //Date picker
            $('#datepicker').datepicker({
                autoclose: true
            });

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass   : 'iradio_minimal-blue'
            });
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass   : 'iradio_minimal-red'
            });
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass   : 'iradio_flat-green'
            });

            //Colorpicker
            $('.my-colorpicker1').colorpicker();
            //color picker with addon
            $('.my-colorpicker2').colorpicker();

            //Timepicker
            $('.timepicker').timepicker({
                showInputs: false
            });
        })
    </script>

@endsection

resources/views/owner/edit.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")


    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Edit owner details</h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Owner</li>
                <li class="active">Edit</li>
            </ol>
        </section>

        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                    {{--<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>--}}
                    <!-- /.box-header -->
                        <div class="box-body">
            <form action="{{route('owner.update',$details["id"])}}" method="POST" name="form">
                {{ csrf_field()}}
                {{ method_field('PATCH')}}
                <div class="form-group">
                    <label>Vehicle Number</label>

                    @if($errors->has('v_no'))
                        <span class="error">  *{{  $errors->first('v_no')}}</span>
                    @endif

                    <select name="v_no[]" class="form-control select2" multiple="multiple"  data-placeholder="Select a Vehicle"
                            style="width: 100%;">
                        <option >Select Vehicle No</option>
                        @foreach($details->v_no as $v_no)
                            <option selected>{{ $v_no }}</option>
                        @endforeach
                        @if(isset($unowned_vehicles))
                        @foreach($unowned_vehicles as $vehicle)
                            <option>{{ $vehicle }}</option>
                        @endforeach
                        @endif
                    </select>
                </div>
                <div class="form-group">
                    <label for="owner-name">Name</label>
                    @if($errors->has('o_name'))
                        <span class="error">  *{{  $errors->first('o_name')}}</span>
                    @endif
                    <input id="owner-name" class="form-control" type="text" name="o_name" placeholder="Eg. Ram Bahadur" value="{{ $details["name"] }}" />
                </div>
                <div class="form-group">
                    <label for="owner-address">Address</label>
                    @if($errors->has('o_address'))
                        <span class="error">  *{{  $errors->first('o_address')}}</span>
                    @endif
                    <input id="owner-address" class="form-control" type="text" name="o_address" placeholder="Eg. Butwal-10" value="{{ $details["address"] }}" />
                </div>
                <div class="form-group">
                    <label for="owner-contact">Contact No.</label>
                    @if($errors->has('o_address'))
                        <span class="error">  *{{  $errors->first('o_address')}}</span>
                    @endif
                    <input id="owner-contact" class="form-control" type="text" name="o_contact" placeholder="Eg. 9811111111" value="{{ $details["contact_no"] }}" />
                </div>
                <div class="form-group">
                    <label for="owner-contact">Insurance</label>
                    <label>
                        <input type="radio" name="insurance" value="1" class="minimal" @if($details->insurance === 1) checked @endif>
                        Yes
                    </label>
                    <label>
                        <input type="radio" name="insurance" value="0" class="minimal" @if($details->insurance === 0) checked @endif>
                        No
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="submit-owner" value="Submit" />
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                </div>
            </form>
                        </div></div></div></div>
        </section>
    </div>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' });
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' });
            //Money Euro
            $('[data-mask]').inputmask();

            //Date range picker
            $('#reservation').daterangepicker();
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A' });
            //Date range as a button
            $('#daterange-btn').daterangepicker(
                {
                    ranges   : {
                        'Today'       : [moment(), moment()],
                        'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month'  : [moment().startOf('month'), moment().endOf('month')],
                        'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate  : moment()
                },
                function (start, end) {
                    $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            );

            //Date picker
            $('#datepicker').datepicker({
                autoclose: true
            });

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass   : 'iradio_minimal-blue'
            });
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass   : 'iradio_minimal-red'
            });
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass   : 'iradio_flat-green'
            });

            //Colorpicker
            $('.my-colorpicker1').colorpicker();
            //color picker with addon
            $('.my-colorpicker2').colorpicker();

            //Timepicker
            $('.timepicker').timepicker({
                showInputs: false
            });
        })
    </script>


@endsection

resources/views/owner/show.blade.php
@extends("../layout/master")
@include("layout.footer")
@include("layout.header")
@include("layout.meta")
@include("layout.side-bar")

@section("main-content")
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Owners
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Owner</a></li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                    {{--<div class="box-header">
                        <h3 class="box-title">Data Table With Full Features</h3>
                    </div>--}}
                    <!-- /.box-header -->
                        <div class="box-body">
                            @if(Session::has('message'))
                                <p class="message"></p>
                                <div class="alert alert-success alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    <h4><i class="icon fa fa-check"></i> Success</h4>
                                    {{ Session::get('message') }}
                                </div>
                            @endif
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S.N</th>
                                    <th>Vehicle Number</th>
                                    <th> Name</th>
                                    <th>Address</th>
                                    <th>Contact</th>
                                    <th>Insurance</th>
                                    <th>Updated Date</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($owners as $owner)
                                    <tr>
                                        <td>{{$loop->index+1 }}</td>
                                        <td>{{ implode(", ",unserialize($owner->v_no)) }}</td>
                                        <td>{{$owner->name}}</td>
                                        <td>{{$owner->address}}</td>
                                        <td>{{$owner->contact_no}}</td>
                                        <td>@if($owner->insurance === 0)No @else Yes @endif</td>
                                        <td>{{$owner->updated_at}}</td>
                                        <td>
                                          @php $type= Auth::user()->user_type; @endphp
                                          @if($type=='admin')
                                            <a href="{{route('owner.edit',$owner->id)}}"><i class="fa fa-fw fa-edit"></i></a>||
                                            <form id="delete-item{{$owner->id}}"  action="{{route('owner.destroy',$owner->id)}}" style="Display:none"  method="post">
                                                {{csrf_field()}}
                                                {{method_field('DELETE')}}

                                            </form>
                                            <a href="" onclick="
                                                    if (confirm('Are you sure, You want to delete this ?'))
                                                    {
                                                    event.preventDefault();
                                                    document.getElementById('delete-item{{$owner->id}}').submit();
                                                    }
                                                    else{
                                                    event.preventDefault();
                                                    }

                                                    ">

                                                <i class="fa fa-fw fa-trash"></i></a>
                                                @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        No data Are Found
                                    </tr>
                                @endforelse
                                </tbody>
                                {{--<tfoot>
                                <tr>
                                    <th>Rendering engine</th>
                                    <th>Browser</th>
                                    <th>Platform(s)</th>
                                    <th>Engine version</th>
                                    <th>CSS grade</th>
                                </tr>
                                </tfoot>--}}
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
    </div>



    <script>
        $(function () {
            $('#example1').DataTable();
            $('#example2').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            });
        })
    </script>
@endsection